name: Go Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release Binary
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18' # Specify the Go version

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build binary
      run: |
        GOOS=linux GOARCH=amd64 go build -o myapp-linux-amd64

    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./kitphishr-linux-amd64
        asset_name: kitphishr-linux-amd64
        asset_content_type: application/octet-stream
