name: Go Build and Release

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch to build from'
        required: true
        default: 'master'

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'  # Specify the Go version

    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branchName }}

    - name: Build binary for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o kitphishr-linux-amd64

    - name: Build binary for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o kitphishr-windows-amd64.exe

    - name: Upload Linux Binary as Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: kitphishr-linux-amd64
        path: ./kitphishr-linux-amd64

    - name: Upload Windows Binary as Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: kitphishr-windows-amd64.exe
        path: ./kitphishr-windows-amd64.exe
