name: Go Build and Release

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows to push commits and upload release assets
      packages: write  # Allows to manage GitHub packages
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'  # Specify the Go version

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build binary for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o kitphishr-linux-amd64

    - name: Build binary for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o kitphishr-windows-amd64.exe

    - name: Upload Linux Release Asset
      if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./kitphishr-linux-amd64
        asset_name: kitphishr-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload Windows Release Asset
      if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./kitphishr-windows-amd64.exe
        asset_name: kitphishr-windows-amd64.exe
        asset_content_type: application/octet-stream
